// AgriTwin — Demo Mode & Simulated Telemetry Badge / Top Banner
import React from 'react';
import { Cpu, AlertCircle } from 'lucide-react';

export function DemoBanner() {
  return (
    <div className="demo-banner">
      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
        <span className="demo-pill">
          <span className="pulse-dot" />
          DEMO MODE
        </span>
        <span style={{ fontWeight: 600 }}>SIMULATED SENSOR DATA — DEMONSTRATION MODE</span>
      </div>
      <div style={{ display: 'none', mdDisplay: 'block', fontSize: '0.74rem', color: '#fef08a' }}>
        Virtual IoT sensor network running &bull; Ready for physical ESP32 gateway integration
      </div>
    </div>
  );
}

export function DemoBadge({ compact = false }) {
  return (
    <span className="demo-pill" title="Sensor data generated by physics-correlated simulation engine">
      <span className="pulse-dot" />
      {compact ? 'SIMULATED' : 'SIMULATED SENSOR DATA'}
    </span>
  );
}

export default DemoBadge;
